[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$d72.5w5B$AwF1daQ4L11OWAvP98C6y1"
  ]

[http.routers.api]
  rule = "Host(`dashboard.opshub.online`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
